Repository PrograMemo-Groom/900pro-be, pull requests merged in 2025-04, with the labels that each got.

#14 Feature/chat : WebSocketConfig에 JWT 핸드셰이크 인터셉터 추가
  src/main/java/programo/_pro/config/WebSocketConfig.java
  src/main/java/programo/_pro/config/jwt/JwtHandshakeInterceptor.java
  src/main/java/programo/_pro/config/jwt/JwtTokenProvider.java
  src/main/java/programo/_pro/config/security/SecurityConfig.java
Labels: 기능추가

#16 Feature/team list : teamList 페이지 api 구현 (정렬, 검색 포함)
  src/main/java/programo/_pro/controller/TeamController.java
  src/main/java/programo/_pro/dto/TeamCardDto.java
  src/main/java/programo/_pro/entity/Level.java
  src/main/java/programo/_pro/entity/Team.java
  src/main/java/programo/_pro/repository/TeamRepository.java
  src/main/java/programo/_pro/service/TeamService.java
Labels: 기능추가

#19 Feature/chat : 채팅 메시지 처리 및 시스템 설계
  src/main/java/programo/_pro/controller/ChatController.java
  src/main/java/programo/_pro/dto/ChatMessageRequest.java
  src/main/java/programo/_pro/dto/ChatMessageResponse.java
  src/main/java/programo/_pro/entity/ChatRoom.java
  src/main/java/programo/_pro/entity/Chatbot.java
  src/main/java/programo/_pro/entity/Message.java
  src/main/java/programo/_pro/entity/TeamMember.java
  src/main/java/programo/_pro/repository/ChatRoomRepository.java
  src/main/java/programo/_pro/repository/ChatbotRepository.java
  src/main/java/programo/_pro/repository/MessageRepository.java
  src/main/java/programo/_pro/repository/TeamMemberRepository.java
  src/main/java/programo/_pro/service/ChatRoomService.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/ChatbotService.java
Labels: 기능추가

#23 Feature/coding test 코드 실행 엔진 (도커) 추가
  compose.override.yaml
  compose.yaml
  docker/README.md
  docker/sandbox/gcc/Dockerfile
  docker/sandbox/gcc/run.sh
  docker/sandbox/java/Dockerfile
  docker/sandbox/java/run.sh
  docker/sandbox/javascript/Dockerfile
  docker/sandbox/javascript/package.json
  docker/sandbox/javascript/run.js
  docker/sandbox/python/Dockerfile
  docker/sandbox/python/run.py
  docker/test.sh
  src/main/java/programo/_pro/controller/CodeExecutorController.java
  src/main/java/programo/_pro/dto/CodeExecutionRequest.java
  src/main/java/programo/_pro/dto/CodeExecutionResponse.java
  src/main/java/programo/_pro/global/ApiResponse.java
  src/main/java/programo/_pro/global/ExecutorException.java
  src/main/java/programo/_pro/global/exception/ExecutorIOException.java
  src/main/java/programo/_pro/global/exception/ExecutorInterruptedException.java
  src/main/java/programo/_pro/global/exception/ExecutorTimeoutException.java
  src/main/java/programo/_pro/service/executor/AbstractExecutorService.java
  src/main/java/programo/_pro/service/executor/CodeExecutorProperties.java
  src/main/java/programo/_pro/service/executor/CodeExecutorService.java
  src/main/java/programo/_pro/service/executor/ErrorHandlingService.java
  src/main/java/programo/_pro/service/executor/ErrorType.java
  src/main/java/programo/_pro/service/executor/ResultParserService.java
  src/main/java/programo/_pro/service/executor/languages/CExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/CppExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/JavaExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/JavaScriptExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/PythonExecutorService.java
  src/main/resources/application.yaml
Labels: 기능추가

#30 Feature/chat : 채팅 기능 개선 및 예외 처리 추가
  src/main/java/programo/_pro/controller/ChatController.java
  src/main/java/programo/_pro/controller/ChatRoomController.java
  src/main/java/programo/_pro/controller/ChatbotController.java
  src/main/java/programo/_pro/global/exception/GlobalExceptionHandler.java
  src/main/java/programo/_pro/global/exception/NotFoundChatException.java
  src/main/java/programo/_pro/service/ChatRoomService.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/ChatbotService.java
Labels: 기능추가

#37 [Fix] Swagger 버그 2차 수정
  build.gradle
  src/main/resources/application.yaml
Labels: 버그

#39 Feature/team : 팀메인 조회, 팀 생성/가입/탈퇴/수정/삭제/팀원 내보내기 api 구현
  src/main/java/programo/_pro/controller/TeamController.java
  src/main/java/programo/_pro/dto/TeamCreateRequest.java
  src/main/java/programo/_pro/dto/TeamMainDto.java
  src/main/java/programo/_pro/dto/TeamMemberDto.java
  src/main/java/programo/_pro/entity/Team.java
  src/main/java/programo/_pro/entity/TeamMember.java
  src/main/java/programo/_pro/entity/User.java
  src/main/java/programo/_pro/global/exception/AlreadyJoinedTeamException.java
  src/main/java/programo/_pro/global/exception/NotFoundTeamException.java
  src/main/java/programo/_pro/global/exception/NotJoinedTeamException.java
  src/main/java/programo/_pro/repository/TeamMemberRepository.java
  src/main/java/programo/_pro/service/TeamService.java
Labels: 기능추가

#42 Feature/chat : 채팅 기능 개선
  src/main/java/programo/_pro/controller/ChatRoomController.java
  src/main/java/programo/_pro/controller/ChatbotController.java
  src/main/java/programo/_pro/dto/ChatMessageRequest.java
  src/main/java/programo/_pro/dto/ChatbotRequest.java
  src/main/java/programo/_pro/entity/ChatRoom.java
  src/main/java/programo/_pro/entity/Chatbot.java
  src/main/java/programo/_pro/service/ChatRoomService.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/ChatbotService.java
Labels: 기능추가

#45 Feature/team : Swagger 문서화 코드추가, responseBody 수정
  src/main/java/programo/_pro/controller/TeamController.java
  src/main/java/programo/_pro/dto/TeamCardDto.java
  src/main/java/programo/_pro/dto/TeamCreateRequest.java
  src/main/java/programo/_pro/dto/TeamMainDto.java
  src/main/java/programo/_pro/dto/TeamMemberDto.java
  src/main/java/programo/_pro/entity/Level.java
  src/main/java/programo/_pro/repository/TeamMemberRepository.java
  src/main/java/programo/_pro/service/TeamService.java
Labels: 기능추가, 리팩토링

#44 Feature/registry 비밀번호 초기화 기능 구현
  src/main/java/programo/_pro/controller/AuthController.java
  src/main/java/programo/_pro/controller/MailController.java
  src/main/java/programo/_pro/controller/UserController.java
  src/main/java/programo/_pro/controller/UserQueueController.java
  src/main/java/programo/_pro/dto/UserDto.java
  src/main/java/programo/_pro/entity/PasswordToken.java
  src/main/java/programo/_pro/entity/User.java
  src/main/java/programo/_pro/repository/PasswordTokenRepository.java
  src/main/java/programo/_pro/service/AuthService.java
  src/main/java/programo/_pro/service/MailService.java
  src/main/java/programo/_pro/service/UserService.java
  src/main/resources/db/schema.sql
Labels: 기능추가

#47 Feature/chat : 채팅 시간대 처리 변경, 채팅방 사용자 이름 표시, 날짜 기반 메시지 조회 기능 및 검색 기능 추가
  src/main/java/programo/_pro/controller/ChatRoomController.java
  src/main/java/programo/_pro/controller/ChatbotController.java
  src/main/java/programo/_pro/dto/ChatMessageResponse.java
  src/main/java/programo/_pro/entity/Chatbot.java
  src/main/java/programo/_pro/entity/Message.java
  src/main/java/programo/_pro/entity/User.java
  src/main/java/programo/_pro/repository/MessageRepository.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/ChatbotService.java
  src/main/java/programo/_pro/service/MessageService.java
Labels: 기능추가

#50 Feature/registry Dto, Exception 폴더로 구분 작업
  src/main/java/programo/_pro/controller/AuthController.java
  src/main/java/programo/_pro/controller/CodeExecutorController.java
  src/main/java/programo/_pro/controller/TeamController.java
  src/main/java/programo/_pro/controller/UserController.java
  src/main/java/programo/_pro/dto/authDto/DupCheckDto.java
  src/main/java/programo/_pro/dto/authDto/SignInDto.java
  src/main/java/programo/_pro/dto/authDto/SignUpDto.java
  src/main/java/programo/_pro/dto/chatDto/ChatMessageRequest.java
  src/main/java/programo/_pro/dto/chatDto/ChatMessageResponse.java
  src/main/java/programo/_pro/dto/codeDto/CodeExecutionRequest.java
  src/main/java/programo/_pro/dto/codeDto/CodeExecutionResponse.java
  src/main/java/programo/_pro/dto/mailDto/EmailRequest.java
  src/main/java/programo/_pro/dto/mailDto/EmailVerficationRequest.java
  src/main/java/programo/_pro/dto/teamDto/TeamCardDto.java
  src/main/java/programo/_pro/dto/teamDto/TeamCreateRequest.java
  src/main/java/programo/_pro/dto/teamDto/TeamMainDto.java
  src/main/java/programo/_pro/dto/teamDto/TeamMemberDto.java
  src/main/java/programo/_pro/dto/userDto/CustomUserDetails.java
  src/main/java/programo/_pro/dto/userDto/UserDto.java
  src/main/java/programo/_pro/dto/userDto/UserInfo.java
  src/main/java/programo/_pro/entity/Team.java
  src/main/java/programo/_pro/global/ExecutorException.java
  src/main/java/programo/_pro/global/exception/GlobalExceptionHandler.java
  src/main/java/programo/_pro/global/exception/chatException/NotFoundChatException.java
  src/main/java/programo/_pro/global/exception/codeException/ExecutorIOException.java
  src/main/java/programo/_pro/global/exception/codeException/ExecutorInterruptedException.java
  src/main/java/programo/_pro/global/exception/codeException/ExecutorTimeoutException.java
  src/main/java/programo/_pro/global/exception/teamException/AlreadyJoinedTeamException.java
  src/main/java/programo/_pro/global/exception/teamException/NotFoundTeamException.java
  src/main/java/programo/_pro/global/exception/teamException/NotJoinedTeamException.java
  src/main/java/programo/_pro/global/exception/userException/NotFoundUserException.java
  src/main/java/programo/_pro/global/filter/JwtAuthenticationFilter.java
  src/main/java/programo/_pro/service/AuthService.java
  src/main/java/programo/_pro/service/ChatRoomService.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/ChatbotService.java
  src/main/java/programo/_pro/service/JwtService.java
  src/main/java/programo/_pro/service/MailService.java
  src/main/java/programo/_pro/service/TeamService.java
  src/main/java/programo/_pro/service/UserService.java
  src/main/java/programo/_pro/service/executor/AbstractExecutorService.java
  src/main/java/programo/_pro/service/executor/CodeExecutorService.java
  src/main/java/programo/_pro/service/executor/ErrorHandlingService.java
  src/main/java/programo/_pro/service/executor/ResultParserService.java
  src/main/java/programo/_pro/service/executor/languages/CExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/CppExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/JavaExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/JavaScriptExecutorService.java
  src/main/java/programo/_pro/service/executor/languages/PythonExecutorService.java
  src/test/java/programo/_pro/controller/AuthControllerTest.java
Labels: 리팩토링

#52 [Chore] yaml, .env 파일 개발, 운영 서버 분리
  .env.dev
  .env.prod
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/db/schema_dev.sql
  src/main/resources/db/schema_prod.sql
Labels: 수정필요x

#54 [Chore] 프로젝트 개발, 운영 yaml, .env 분리
  .gitignore
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/db/schema_dev.sql
  src/main/resources/db/schema_prod.sql
Labels: 수정필요x

#55 Feature/mypage 회원탈퇴 기능
  src/main/java/programo/_pro/config/security/SecurityConfig.java
  src/main/java/programo/_pro/controller/AuthController.java
  src/main/java/programo/_pro/controller/HistoryController.java
  src/main/java/programo/_pro/controller/MyPageController.java
  src/main/java/programo/_pro/controller/UserController.java
  src/main/java/programo/_pro/dto/AuthenticationToken.java
  src/main/java/programo/_pro/dto/JwtUserInfoDto.java
  src/main/java/programo/_pro/dto/authDto/DupCheckDto.java
  src/main/java/programo/_pro/dto/authDto/SignInDto.java
  src/main/java/programo/_pro/dto/authDto/SignUpDto.java
  src/main/java/programo/_pro/dto/userDto/UserInfoUpdateDto.java
  src/main/java/programo/_pro/global/filter/JwtAuthFilter.java
  src/main/java/programo/_pro/global/filter/JwtAuthenticationFilter.java
  src/main/java/programo/_pro/service/CustomUserDetailsService.java
  src/main/java/programo/_pro/service/HistoryService.java
  src/main/java/programo/_pro/service/JwtService.java
  src/main/java/programo/_pro/service/MyPageService.java
Labels: 기능추가

#61 Feature/history 형변환 오류 긴급 조치
  src/main/java/programo/_pro/config/security/SecurityConfig.java
  src/main/java/programo/_pro/controller/HistoryController.java
  src/main/java/programo/_pro/global/filter/JwtAuthFilter.java
  src/main/java/programo/_pro/service/HistoryService.java
  src/main/resources/db/schema_prod.sql
Labels: 버그

#63 Feature/history 500에러 해결 및 JWT 토큰
  .gitignore
  build.gradle
  src/main/java/programo/_pro/config/security/SecurityConfig.java
  src/main/java/programo/_pro/dto/AuthenticationToken.java
  src/main/java/programo/_pro/dto/authDto/SignUpDto.java
  src/main/java/programo/_pro/dto/userDto/CustomUserDetails.java
  src/main/java/programo/_pro/dto/userDto/UserInfo.java
  src/main/java/programo/_pro/entity/Level.java
  src/main/java/programo/_pro/entity/Team.java
  src/main/java/programo/_pro/entity/TeamMember.java
  src/main/java/programo/_pro/global/exception/GlobalExceptionHandler.java
  src/main/java/programo/_pro/global/exception/userException/NotFoundUserException.java
  src/main/java/programo/_pro/global/exception/userException/UserException.java
  src/main/java/programo/_pro/global/filter/JwtAuthenticationFilter.java
  src/main/java/programo/_pro/service/CustomUserDetailsService.java
  src/main/java/programo/_pro/service/JwtService.java
  src/main/java/programo/_pro/service/MailService.java
  src/main/java/programo/_pro/service/MyPageService.java
  src/main/java/programo/_pro/service/TeamService.java
  src/main/java/programo/_pro/service/UserService.java
Labels: 버그

#72 Update/history getHistory 요청값 testId -> teamId, 테스트 날짜 (2025-04-24 형식)
  src/main/java/programo/_pro/controller/HistoryController.java
  src/main/java/programo/_pro/dto/chatDto/ChatMessageResponse.java
  src/main/java/programo/_pro/entity/Chatbot.java
  src/main/java/programo/_pro/entity/Message.java
  src/main/java/programo/_pro/entity/Test.java
  src/main/java/programo/_pro/repository/TestRepository.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/HistoryService.java
  src/main/resources/db/schema_dev.sql
  src/main/resources/db/schema_prod.sql
Labels: 기능추가

#75 Feature/waitingroom 랜덤 문제 조회 및 DB 반영 기능 구현
  src/main/java/programo/_pro/Application.java
  src/main/java/programo/_pro/controller/MailController.java
  src/main/java/programo/_pro/controller/WaitingRoomController.java
  src/main/java/programo/_pro/dto/problemDto/ProblemDto.java
  src/main/java/programo/_pro/dto/problemDto/ProblemGenerateRequestDto.java
  src/main/java/programo/_pro/entity/Team.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/WaitingRoomService.java
  src/main/resources/db/schema_dev.sql
  src/main/resources/db/schema_prod.sql
Labels: 기능추가

#76 examEndApi 코딩테스트 페이지 시험 종료 api 생성
  src/main/java/programo/_pro/controller/CodeController.java
  src/main/java/programo/_pro/controller/HistoryController.java
  src/main/java/programo/_pro/dto/codeDto/CodeRequestDto.java
  src/main/java/programo/_pro/dto/codeDto/UpdateCodeDto.java
  src/main/java/programo/_pro/entity/User.java
  src/main/java/programo/_pro/repository/CodeRepository.java
  src/main/java/programo/_pro/service/CodeService.java
  src/main/java/programo/_pro/service/MyPageService.java
  src/main/resources/db/schema_dev.sql
  src/main/resources/db/schema_prod.sql
Labels: 기능추가

#80 [Refactor/chat] Redis 잔존 코드 삭제 또는 주석처리, 실시간 채팅 유저 닉네임 매핑 문제 해결
  build.gradle
  src/main/java/programo/_pro/config/RedisConfig.java
  src/main/java/programo/_pro/config/WebSocketConfig.java
  src/main/java/programo/_pro/controller/UserQueueController.java
  src/main/java/programo/_pro/global/filter/WaitingFilter.java
  src/main/java/programo/_pro/service/ChatService.java
  src/main/java/programo/_pro/service/JwtService.java
  src/main/java/programo/_pro/service/RedisService.java
  src/main/java/programo/_pro/service/UserQueueService.java
  src/main/java/programo/_pro/service/chatredis/ChatMessageListener.java
  src/main/java/programo/_pro/service/chatredis/ChatPublisherService.java
Labels: 리팩토링, 버그
